/**
 * generate_dosen_sync.cjs
 * Reads DATABASE DOSEN LECTRA.xlsx and generates:
 *   1. supabase/migrations/25_add_dosen_columns.sql  (ALTER TABLE)
 *   2. supabase/migrations/26_sync_dosen_from_excel.sql  (UPSERT data)
 */

const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

// ─── CONFIG ──────────────────────────────────────────────────────────────────
const EXCEL_PATH = path.resolve(__dirname, '../contohExcel/DATABASE DOSEN LECTRA.xlsx');
const OUT_DIR    = path.resolve(__dirname, '../supabase/migrations');

// ─── LOKER PARSER ─────────────────────────────────────────────────────────────
/**
 * Parse LOKER string → { prodi, fakultas }
 * Examples:
 *   "PROGRAM STUDI S1 INFORMATIKA (FIF)"            → { prodi: 'S1 INFORMATIKA', fakultas: 'FIF' }
 *   "PROGRAM STUDI S1 INFORMATIKA KAMPUS SURABAYA"  → { prodi: 'S1 INFORMATIKA', fakultas: 'TUS' }
 */
function parseLoker(loker) {
  if (!loker) return { prodi: null, fakultas: null };

  const raw = loker.trim();

  // Remove leading "PROGRAM STUDI " prefix (case-insensitive)
  const withoutPrefix = raw.replace(/^PROGRAM\s+STUDI\s+/i, '').trim();

  // Pattern 1: ends with (FAK_CODE)  e.g. "S1 INFORMATIKA (FIF)"
  const matchFak = withoutPrefix.match(/^(.+?)\s*\(([A-Z]+)\)\s*$/);
  if (matchFak) {
    return {
      prodi: matchFak[1].trim(),
      fakultas: matchFak[2].trim(),
    };
  }

  // Pattern 2: contains KAMPUS XXX at end
  const matchKampus = withoutPrefix.match(/^(.+?)\s+KAMPUS\s+(SURABAYA|PURWOKERTO|JAKARTA)\s*$/i);
  if (matchKampus) {
    const kampus = matchKampus[2].toUpperCase();
    const fakultasMap = {
      SURABAYA:  'TUS',
      PURWOKERTO:'TUP',
      JAKARTA:   'TUJ',
    };
    // Keep kampus info in prodi name for clarity
    return {
      prodi: matchKampus[1].trim() + ' KAMPUS ' + kampus,
      fakultas: fakultasMap[kampus],
    };
  }

  // Fallback: use full string as prodi, no fakultas
  console.warn('⚠️  Cannot parse LOKER:', raw);
  return { prodi: withoutPrefix, fakultas: null };
}

// ─── ESCAPE SQL STRING ────────────────────────────────────────────────────────
function esc(val) {
  if (val === null || val === undefined) return 'NULL';
  return `'${String(val).replace(/'/g, "''")}'`;
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────
function main() {
  console.log('📖  Reading Excel…');
  const wb = XLSX.readFile(EXCEL_PATH);
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1 });

  // Skip header row
  const dataRows = rows.slice(1).filter(r => r[0] || r[1]); // must have NIP or NAMA

  console.log(`✅  Found ${dataRows.length} dosen rows`);

  // ── Migration 25: Add new columns ─────────────────────────────────────────
  const sql25 = `-- 25_add_dosen_columns.sql
-- Adds nuptk column to dosen table (non-destructive)
-- Note: program_studi and fakultas already exist; loker is parsed into those two columns

ALTER TABLE public.dosen
  ADD COLUMN IF NOT EXISTS nuptk TEXT;

COMMENT ON COLUMN public.dosen.nuptk IS 'Nomor Unik Pendidik dan Tenaga Kependidikan';
`;

  // ── Migration 26: UPSERT all dosen ────────────────────────────────────────
  const lines = [];
  lines.push(`-- 26_sync_dosen_from_excel.sql`);
  lines.push(`-- Generated by scripts/generate_dosen_sync.cjs`);
  lines.push(`-- Source: DATABASE DOSEN LECTRA.xlsx (${dataRows.length} rows)`);
  lines.push(`-- Strategy: ON CONFLICT (nip) DO UPDATE → safe to re-run`);
  lines.push(``);
  lines.push(`INSERT INTO public.dosen`);
  lines.push(`  (id, nip, nama, jabatan_fungsional, nuptk, status, program_studi, fakultas)`);
  lines.push(`VALUES`);

  const valueLines = [];
  let skipped = 0;

  for (const row of dataRows) {
    const nip     = row[0] ? String(row[0]).trim() : null;
    const nama    = row[1] ? String(row[1]).trim() : null;
    const jabatan = row[2] ? String(row[2]).trim() : null;
    const nuptk   = row[3] ? String(row[3]).trim() : null;
    const status  = row[4] ? String(row[4]).trim() : null;
    const lokerRaw= row[5] ? String(row[5]).trim() : null;

    if (!nip && !nama) { skipped++; continue; }

    const { prodi, fakultas } = parseLoker(lokerRaw);

    valueLines.push(
      `  (gen_random_uuid(), ${esc(nip)}, ${esc(nama)}, ${esc(jabatan)}, ${esc(nuptk)}, ${esc(status)}, ${esc(prodi)}, ${esc(fakultas)})`
    );
  }

  lines.push(valueLines.join(',\n'));
  lines.push(`ON CONFLICT (nip) DO UPDATE SET`);
  lines.push(`  nama               = EXCLUDED.nama,`);
  lines.push(`  jabatan_fungsional = EXCLUDED.jabatan_fungsional,`);
  lines.push(`  nuptk              = EXCLUDED.nuptk,`);
  lines.push(`  status             = EXCLUDED.status,`);
  lines.push(`  program_studi      = EXCLUDED.program_studi,`);
  lines.push(`  fakultas           = EXCLUDED.fakultas,`);
  lines.push(`  updated_at         = NOW();`);
  lines.push(``);
  lines.push(`-- Done. Total rows processed: ${dataRows.length}, skipped (empty): ${skipped}`);

  const sql26 = lines.join('\n');

  // ── Write files ───────────────────────────────────────────────────────────
  const out25 = path.join(OUT_DIR, '25_add_dosen_columns.sql');
  const out26 = path.join(OUT_DIR, '26_sync_dosen_from_excel.sql');

  fs.writeFileSync(out25, sql25, 'utf8');
  fs.writeFileSync(out26, sql26, 'utf8');

  console.log(`✅  Written: ${out25}`);
  console.log(`✅  Written: ${out26} (${valueLines.length} dosen)`);
  console.log(`⚠️  Skipped empty rows: ${skipped}`);
}

main();
